apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ravi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: myapp
      namespace: ravi
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp-container
        image: ravikumargopal/ravi-app 
