apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: ravi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vote
  template:
    metadata:
      name: vote
      namespace: ravi
      labels:
        name: vote
    spec:
      containers:
      - name: vote-container
        image: ravikumargopal/vote-ravi
