apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ravi-deploy
  labels: 
    name: ravi-label
    type: ravi-type
  namespace: ravi-ns
spec: 
  template: 
    metadata:
      name: nginx
      labels:
        name: ravi-label
        type: ravi-type
      namespace: ravi-ns

    spec:
      containers:
        - name: nginx-demo
          image: nginx:1.17
      nodeSelector:
         type: ravi-type

  replicas: 3
  selector: 
    matchLabels: 
      name: ravi-label
      type: ravi-type

