apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ravi-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ravi-group-role
roleRef:
  kind: ClusterRole
  name: ravi-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: manager
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ravi-user-role
  namespace: ravi-ns
roleRef:
  kind: ClusterRole
  name: ravi-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ravi
  apiGroup: rbac.authorization.k8s.io
