apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ravi-ns
  name: ravi-role
rules:
- apiGroups: [""] # "" indicates the core API (v1, apps/v1)
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ravi-ns
  name: ravi-read-pod
roleRef:
  kind: Role
  name: ravi-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: Ravi
  apiGroup: rbac.authorization.k8s.io
