apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ravi-ns
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
  selector:
    app: jenkins
---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: ravi-ns
  labels:
    app: jenkins
spec:
  volumes:
    - name: jenkins-pv-storage
      persistentVolumeClaim:
        claimName: jenkins-pv-claim
  containers:
    - name: jenkins-pv-container
      image: jenkins/jenkins:lts
      volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: jenkins-pv-storage



