apiVersion: v1
kind: Pod
metadata:
  name: ravi-pod
  namespace: ravi-ns
spec:
  containers:
  - name: ravi-cont
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env" ] 
    envFrom:
    - configMapRef:
        name: game-config
  restartPolicy: Never 
