apiVersion: v1
kind: Pod
metadata:
  name: ravi-pod
  namespace: ravi-ns
spec:
  containers:
  - name: ravi-containder
    image: ravikumargopal/demorepo:httpd
  imagePullSecrets:
  - name: ravi-secrets
