apiVersion: v1
kind: Pod
metadata:
  name: ravi-secret
  labels:
    name: ravi-secret
  namespace: ravi-ns
spec:
  volumes:
  - name: secret-volume
    secret: 
      secretName: ravi-secret
  containers:
  - name: ravi-secret-cont
    image: httpd
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
      

