apiVersion: v1
kind: Pod
metadata:
  name: ravi-pod
  namespace: ravi-ns
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: ravi-cont
    image: bash
    command: [ "/bin/bash", "-c", "env" ]
    securityContext:
      allowPrivilegeEscalation: true
