apiVersion: v1
kind: Service
metadata:
   name: ravi-new-deploy
   namespace: ravi-ns
spec:
  type: NodePort
  selector:
    name: ravi-new-label
    type: ravi-type
  ports:
   - protocol: TCP
     port: 85
     targetPort: 80
---  
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ravi-new-deploy
  labels: 
    name: ravi-new-label
    type: ravi-type
  namespace: ravi-ns
spec: 
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
  template: 
    metadata:
      name: httpd_ravi
      labels:
        name: ravi-new-label
        type: ravi-type
      namespace: ravi-ns

    spec:
      containers:
        - name: httpd-demo
          image: nginx

      nodeSelector:
         type: ravi-type

  replicas: 2
  selector: 
    matchLabels: 
      name: ravi-new-label
      type: ravi-type

