apiVersion: v1
kind: Pod
metadata:
  name: ravi-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
           matchExpressions:
           - key: label
             operator: In
             values:
             - ravi-label1
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0


  
