apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: ravi-rs
  labels: 
    name: ravi-rs
    type: back-end
  namespace: ravi-ns
spec: 
  template: 
    metadata:
      name: nginx
      labels:
        name: ravi-rs
        type: back-end
      namespace: ravi-ns

    spec:
      containers:
        - name: nginx-demo
          image: nginx

  replicas: 2
  selector: 
    matchLabels: 
      name: ravi-rs
      type: back-end

